# Copyright 2024 Circle Internet Group, Inc. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Coverage
on:
  pull_request:
    types: [labeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run_coverage:
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'needs_coverage' }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Check out repository code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Setup CI Environment
        uses: ./.github/composite-actions/setup-ci

      - name: Compile contracts
        run: yarn compile

      - name: Run coverage
        run: yarn coverage

      - name: Report coverage to PR
        id: report-coverage
        uses: sidx1024/report-nyc-coverage-github-action@8adfb1be4a23deee7b1eaf0dc3000317eedaeab5 # v1.2.7
        with:
          coverage_file: "coverage/coverage-summary.json"
          base_coverage_file: ""
          comment_template_file: ".github/resources/coverage-report-template.md"

      - name: Check coverage
        if: |
          fromJSON(steps.report-coverage.outputs.total_lines_coverage_percent_raw) < 100 ||
          fromJSON(steps.report-coverage.outputs.total_branches_coverage_percent_raw) < 98 ||
          fromJSON(steps.report-coverage.outputs.total_statements_coverage_percent_raw) < 100 ||
          fromJSON(steps.report-coverage.outputs.total_functions_coverage_percent_raw) < 100
        uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7.1.0
        with:
          script: |
            core.setFailed('Test coverage is under the threshold')
